export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';
export const GET_COMPANIES_LIST = 'GET_COMPANIES_LIST';
export const GET_COMPANIES_LIST_ERROR = 'GET_COMPANIES_LIST_ERROR';
export const GET_PERSONAL_INFO = 'GET_PERSONAL_INFO';
export const GET_PERSONAL_INFO_ERROR = 'GET_PERSONAL_INFO_ERROR';
export const GET_DASHBOARD_INFO = 'GET_DASHBOARD_INFO';
export const GET_DASHBOARD_INFO_ERROR = 'GET_DASHBOARD_INFO_ERROR';
